# Generated by Django 6.0.4 on 2026-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='en_attente', max_length=50),
        ),
    ]
