# Generated by Django 6.0.4 on 2026-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_add_checkout_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='address',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='note',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='skin_problem',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='skin_type',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ville',
        ),
        migrations.AlterField(
            model_name='articlecommande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
