# Generated by Django 4.2 on 2026-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_remove_commande_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmer', 'Confirmée'), ('rejeter', 'Rejetée')], default='en_attente', max_length=50),
        ),
    ]
