# Generated by Django 4.2 on 2026-05-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='full_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='commande',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='quartier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='skin_problem',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='skin_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville',
            field=models.CharField(default='', max_length=120),
        ),
    ]
