# Generated by Django 4.2 on 2026-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_favori',
            field=models.ImageField(blank=True, null=True, upload_to='produits/favoris/', verbose_name='Image spéciale favoris'),
        ),
    ]
