# Generated by Django 4.2 on 2026-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_image_favori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image_favori',
        ),
        migrations.AddField(
            model_name='produit',
            name='is_favori',
            field=models.BooleanField(default=False, verbose_name='Produit favori (Curated Favourite)'),
        ),
    ]
