# Generated by Django 4.2.30 on 2026-04-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_categorie_id_alter_produit_id'),
        ('produit', '0005_remove_produit_image_favori_produit_is_favori'),
    ]

    operations = [
    ]
