# Generated by Django 4.2 on 2026-05-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_alter_categorie_id_alter_produit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='score_etoiles',
            field=models.IntegerField(choices=[(0, '0 étoile'), (1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=0, help_text='Score de 0 à 5 étoiles pour les produits favoris', verbose_name='Score (étoiles)'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
