# Generated by Django 6.0.4 on 2026-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0003_alter_articlepanier_id_alter_panier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepanier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
