# Generated by Django 4.2 on 2026-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_recommandation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia_recommandation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
