# Generated by Django 6.0.4 on 2026-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_recommandation', '0003_alter_ia_recommandation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ia_recommandation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
