# Generated by Django 4.2.30 on 2026-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
