# Generated by Django 4.2.30 on 2026-04-28 23:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0007_alter_categorie_id_alter_produit_id'),
        ('avis', '0004_alter_avis_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('utilisateur', 'produit')},
        ),
    ]
